config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'gists#index'
  resources :gists do
    get :autocomplete_user_name, :on => :collection 
                 end
  resources :pages 
   post 'result' => 'gists#search'

end

app/models/gist.rb
class Gist < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gists

  def self.search(query)
    if query
      where(["name LIKE ?", "%#{query}%"])
    else
       all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  autocomplete :user, :name

  # GET /gists
  # GET /gists.json
  def index
    @users = User.all
    @gists = Gist.where(user_id: current_user.id)
  end

  # GET /gists/1
  # GET /gists/1.json
  def show
  end

  # GET /gists/new
  def new
    @gist = Gist.new
  end

  # GET /gists/1/edit
  def edit
  end

  # POST /gists
  # POST /gists.json
  def create
    @gist = Gist.new(gist_params)

    respond_to do |format|
      if @gist.save
        format.html { redirect_to "/", notice: 'Gist was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @gists.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gists/1
  # PATCH/PUT /gists/1.json
  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to "/", notice: 'Gist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gists/1
  # DELETE /gists/1.json
  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url, notice: 'Gist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @users = User.search(params[:query])
    render "result"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gist
      @gist = Gist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:gist).permit(:title, :content, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

	def show
	@user = User.find(params[:id])
	@gists = Gist.where(user_id: @user.id)
	end

	def new
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gists/_form.html.erb
<%= simple_form_for(@gist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<div class="row">
	    <div class="col-md-12">
	      <%= f.input :title, label: false, input_html:{class: "form-control", placeholder: "title"} %>
	    </div>
  	</div>
  	<br>
  	<div class="row">
	    <div class="col-md-12">
	      <%= f.input :content, label: false, input_html:{class: "tinymce", rows: 20, cols: 60} %>
	    </div>
  	</div>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
<%= tinymce %>

app/views/gists/edit.html.erb
<div class="row">
	<div class="col-md-3 col-md-offset-5">
	  <h1>Editing Gist</h1>
	</div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @gist %> |
<%= link_to 'Back', gists_path %>

app/views/gists/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>welcome <%= current_user.name %></h1>
  </div>
  <div class="col-md-4 text-right">
    <%= link_to 'New Gist', new_gist_path, class: "btn btn-default" %>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_tag "/result", method: :post  do %>
      <%= autocomplete_field_tag "query",  params[:query],autocomplete_user_name_gists_path, :size => 30 %>
      <%= submit_tag "Search", class:"button radius"%>
    <% end %>
  </div>
</div>
<table>
  <tbody>
    <% @gists.each do |gist| %>
      <tr>
        <td><%= link_to gist.title, edit_gist_path(gist)  %></td>
        <td> Submitted <%= time_ago_in_words(gist.created_at) %> by <%= gist.user.name %> </td>
        <td><%= link_to 'Show', gist %></td>
        <td><%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/gists/new.html.erb
<h1>New Gist</h1>

<%= render 'form' %>

<%= link_to 'Back', gists_path %>

app/views/gists/result.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Resultat</h1>
      <% @users.each do |user| %>
        <p ><a href="/pages/<%= user.id %>"><%= user.name %></a></p>
      <% end %>
    <a href="/">Retour</a>
  </div>
</div>

app/views/gists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gist.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @gist.content.html_safe %>
</p>

<%= link_to 'Edit', edit_gist_path(@gist) %> |
<%= link_to 'Back', gists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row">
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		  	<div class="col-md-2">
            <a class="navbar-brand" href="/">My GIST</a>
		    </div>
	      <div class="col-md-3 col-md-offset-7">
          <ul>
				    <% if user_signed_in? %>
				      <%= link_to 'Account', edit_user_registration_path, class: "btn btn-default navbar-btn" %>
				      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "btn btn-default navbar-btn" %>
				    <% else %>
				      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-default navbar-btn" %>
				      <%= link_to 'Sign in', new_user_session_path, class: "btn btn-default navbar-btn" %>
				    <% end %>
	        </ul>
		    </div>
		  </div>
		</nav>
	</div>

<%= yield %>

</body>
</html>

app/views/pages/new.html.erb
<h1>New pages</h1>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1><%= @user.name %>'s Page</h1>
  </div>
</div>
<table>
  <tbody>
    <% @gists.each do |gist| %>
      <tr>
        <td><%= link_to gist.title, edit_gist_path(@user)  %></td>
        <td> Submitted <%= time_ago_in_words(gist.created_at) %> by <%= gist.user.name %> </td>
        <td><%= link_to 'Show', gist %></td>
        <td><%= link_to 'Destroy', gist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>